# Generated by Django 4.0.6 on 2022-07-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('block_no', models.CharField(max_length=50, null=True)),
                ('house_no', models.CharField(max_length=50, null=True)),
                ('about_me', models.TextField(max_length=5000, null=True)),
                ('pic', models.FileField(default='media/images/default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField(default=459)),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verfied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=50)),
                ('e_pic', models.FileField(null=True, upload_to='media/images/notice')),
                ('e_venue', models.CharField(max_length=2000)),
                ('e_date', models.DateField(max_length=10)),
                ('e_content', models.TextField(max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
        migrations.AddField(
            model_name='chairman',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Add_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('n_pic', models.FileField(null=True, upload_to='media/images/notice')),
                ('n_video', models.FileField(null=True, upload_to='media/video')),
                ('content', models.TextField(max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
        migrations.CreateModel(
            name='Add_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_f_name', models.CharField(max_length=50)),
                ('m_l_name', models.CharField(max_length=50)),
                ('m_email', models.EmailField(max_length=50)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=15)),
                ('work', models.CharField(max_length=50, null=True)),
                ('m_block_no', models.CharField(max_length=50, null=True)),
                ('m_house_no', models.CharField(max_length=50, null=True)),
                ('family_member', models.IntegerField(null=True)),
                ('vehicle', models.IntegerField(null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('m_about_me', models.TextField(max_length=5000, null=True)),
                ('m_pic', models.FileField(default='media/images/member/m_default.png', upload_to='')),
                ('m_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
