# Generated by Django 4.0.6 on 2022-07-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_member',
            name='m_email',
        ),
    ]
